### ISSUE TITLE
ATAC notebook errors

### ISSUE THREAD

**Issue by BKover99** [cellatlas/cellatlas#1]
Hi I’ve been trying to find a tool to do large-scale rapid uniform pre-processing for ATAC data. I thought snATAK through cellatlas would be a good way to do it and started working through your Jupyter notebook (https://github.com/cellatlas/cellatlas/blob/main/examples/atac-10xatac/preprocess.ipynb), and then planning to use it on my own data. However, I got stuck at multiple points in the Jupyter notebook, and so I am wondering if you could help me.

the line 

`!seqspec print spec.yaml`

returned

/bin/bash: line 1: seqspec: command not found

and 

```
!cellatlas build -o out \
-m rna \
-s spec.yaml \
-fa $FA -g $GTF \
fastqs/R1.fastq.gz fastqs/R2.fastq.gz
```

returned

Traceback (most recent call last):
  File "/usr/local/bin/cellatlas", line 5, in <module>
    from cellatlas.main import main
  File "/usr/local/lib/python3.10/dist-packages/cellatlas/main.py", line 4, in <module>
    from .cellatlas_build import setup_build_args, validate_build_args
  File "/usr/local/lib/python3.10/dist-packages/cellatlas/cellatlas_build.py", line 6, in <module>
    from seqspec.seqspec_onlist import run_onlist
ModuleNotFoundError: No module named 'seqspec'

I am guessing it all has to do with how seqspec is installed, but then I wasn't sure from where and how I would install the correct version. Thanks for any help in advance!

**Comment by chesnov** [comment]
If this is still relevant for you, try using the command I posted in #2 - it is a specific commit of seqspec that works.
