### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gibberwocky** [cellatlas/cellatlas#2]
Hi

I'm looking forward to using cellatlas. I've installed it as follows:

```module load mamba
mamba create --name cellatlas
mamba activate cellatlas
mamba install git pip
pip install git+https://github.com/cellatlas/cellatlas.git
```

Running `seqspec` shows that it has installed during this process, and shows help:

```
$ seqspec
usage: seqspec [-h] <CMD> ...

seqspec 0.3.1: A machine-readable file format for genomic library sequence and structure.

GitHub: https://github.com/pachterlab/seqspec
Documentation: https://pachterlab.github.io/seqspec/

positional arguments:
  <CMD>
    check     Validate seqspec file against specification
    find      Find objects in seqspec file
    file      List files present in seqspec file
    format    Autoformat seqspec file
    index     Identify position of elements in seqspec file
    info      Get information from seqspec file
    init      Generate a new seqspec file
    methods   Convert seqspec file into methods section
    modify    Modify attributes of various elements in seqspec file
    onlist    Get onlist file for elements in seqspec file
    print     Display the sequence and/or library structure from seqspec file
    split     Split seqspec file by modality
    version   Get seqspec tool version and seqspec file version

options:
  -h, --help  show this help message and exit
```

However, if I attempt to run cellatlas with no parameters to test it works and shows help (https://github.com/cellatlas/cellatlas/blob/main/cellatlas/main.py) then I get the following:

```
$ cellatlas build
Traceback (most recent call last):
  File "/uoa/home/s14dw4/sharedscratch/.conda/envs/cellatlas/bin/cellatlas", line 5, in <module>
    from cellatlas.main import main
  File "/uoa/home/s14dw4/sharedscratch/.conda/envs/cellatlas/lib/python3.13/site-packages/cellatlas/main.py", line 4, in <module>
    from .cellatlas_build import setup_build_args, validate_build_args
  File "/uoa/home/s14dw4/sharedscratch/.conda/envs/cellatlas/lib/python3.13/site-packages/cellatlas/cellatlas_build.py", line 9, in <module>
    from seqspec.seqspec_find import run_find_by_type
ImportError: cannot import name 'run_find_by_type' from 'seqspec.seqspec_find' (/uoa/home/s14dw4/sharedscratch/.conda/envs/cellatlas/lib/python3.13/site-packages/seqspec/seqspec_find.py)
```

So the installation appears to be missing something. Any thoughts on how to resolve this?

Thanks!

**Comment by sbooeshaghi** [comment]
Hi- cellatlas was written with a prior version of seqspec. major updates to seqspec have been made which necessitate modifications to cellatlas. I've not had time yet to make those changes. If you'd like to take a stab at it, the seqspec documentation is thorough: https://pachterlab.github.io/seqspec/

**Comment by gibberwocky** [comment]
Thanks, I've taken a **very** quick look, and changing ```from seqspec.seqspec_find import run_find_by_type``` to ```from seqspec.seqspec_find import run_find``` in  both ```cellatlas_build.py``` and ```UniformData.py``` gets the help to show.

```
$ cellatlas build --help
usage: cellatlas build [-h] [-o OUT [OUT ...]] [-s SEQSPEC [SEQSPEC ...]]
                       [-fa FASTA] [-fb Feature barcodes] [-g GTF]
                       [-m Modality [Modality ...]] [--joint]
                       fastqs [fastqs ...]

build cellatlas for one observation

positional arguments:
  fastqs                List of FASTQ files

optional arguments:
  -h, --help            show this help message and exit
  -o OUT [OUT ...]      Path(s) to output file
  -s SEQSPEC [SEQSPEC ...]
                        Path to seqspec file(s)
  -fa FASTA             Path to genome fasta file
  -fb Feature barcodes  Path to feature barcode file
  -g GTF                Path to genome gtf file
  -m Modality [Modality ...]
                        Modality of the data
  --joint               Joint quantification
```

I'll work through a couple of examples to see if I hit any more bumps.

**Comment by gibberwocky** [comment]
> Hi- cellatlas was written with a prior version of seqspec. major updates to seqspec have been made which necessitate modifications to cellatlas. I've not had time yet to make those changes. If you'd like to take a stab at it, the seqspec documentation is thorough: https://pachterlab.github.io/seqspec/

Which release of seqspec is the current release of cellatlas based on?

**Comment by chesnov** [comment]
> > Hi- cellatlas was written with a prior version of seqspec. major updates to seqspec have been made which necessitate modifications to cellatlas. I've not had time yet to make those changes. If you'd like to take a stab at it, the seqspec documentation is thorough: https://pachterlab.github.io/seqspec/
> 
> Which release of seqspec is the current release of cellatlas based on?

I think it is an in-between releases commit. This one worked for me: 
`!pip install git+https://github.com/pachterlab/seqspec.git@9471a317f524c289ee6582c1889cdeac0c5396b2`
